runtime: python27
api_version: 1
threadsafe: true
service: echolog

handlers:
- url: /echolog
  script: main.app

libraries:
- name: ssl
  version: latest

env_variables:
    GAE_USE_SOCKETS_HTTPLIB : 'true'