runtime: python27
api_version: 1
threadsafe: true
service: echolog

handlers:
- url: /echolog
  script: main.app
- url: /echolog/ui
  static_files: static/index.html
  upload: static/index.html
- url: /echolog/static
  static_dir: static

libraries:
- name: ssl
  version: latest

env_variables:
    GAE_USE_SOCKETS_HTTPLIB : 'true'