runtime: python27
api_version: 1
threadsafe: true
service: echolog

handlers:
- url: /echolog
  script: main.app
- url: /echolog/ui
  static_files: ui/index.html
  upload: ui/index.html
- url: /echolog/ui/(.*)$
  static_files: ui/\1
  upload: ui/\1

libraries:
- name: ssl
  version: latest

env_variables:
    GAE_USE_SOCKETS_HTTPLIB : 'true'